apiVersion: v1
kind: Service
metadata:
  name: db-srv
spec:
  type: ClusterIP
  ports:
    - port: 8890
      targetPort: 8890
      protocol: TCP
  selector:
    app: db


#  sessionAffinity: ClientIP
#  sessionAffinityConfig:
#    clientIP:
#      timeoutSeconds: 3600